[package]
name = "e_2022_65"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fraction = "0.11.0"

# [dependencies.math_arsenal]
# path = "/home/lemark/Projets/rust/math_arsenal"