[package]
name = "e_2022_49"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primal = "0.3"
itertools = "0.10.3"
digits_iterator = "0.1.0"

[profile.dev]
opt-level = 3
